version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo_db:
    image: mongo:4.0
    restart: always
    ports: [ "27017:27017" ]
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.adminCommand({ping:1})' | mongo --quiet" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user_api_service:
    build:
      context: 5/api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app


  service_api_service:
    build:
      context: 5/service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./service:/app
